---
- name: Install and configure webserver
  hosts: nodes
  become: yes
  tasks:
    - name: Install apache
      apt:
        name:
          - apache2
        state: latest
    - name : Enable and start service
      service: 
        name : apache2
        enabled : true
        state : started 